version: '3'
services:

  db:
    restart: always
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-sound_fingerprints}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
    networks:
      - project

  redis:
    restart: always
    image: "redis:alpine"
    command: redis-server --appendonly yes --replica-read-only no --requirepass ${REDIS_PASSWORD:-passwd}
    ports:
        - "6379:6379"
    depends_on:
      - db
    networks:
      - project

volumes:
  db_data:

networks:
  project:
